SUI_RPC = "https://mainnet.sui.rpcpool.com/"

THREAD_START_SLEEP_IN_SEC = [10, 20]
SMALL_SLEEP_BETWEEN_ACTIONS_IN_SEC = [2, 4]
BIG_SLEEP_BETWEEN_ACTIONS_IN_SEC = [60, 300]

COINFLIP_COUNT_PER_SESSION = [1, 2]
SUILETTE_COUNT_PER_SESSION = [1, 2]

SHUFFLE_ACCOUNTS = True
